[tool.pytest.ini_options]

[tool.ruff]
line-length = 120
target-version = "py312" # since PYTHON_VERSION=python3.12 in base/Dockerfile

[tool.ruff.lint]
select = ["E", "F", "FLY", "ICN", "Q", "RUF", "UP", "W"]
exclude = ["*.ipynb"]

[tool.ruff.lint.per-file-ignores]
"**/*test*.py" = ["E402", "F811"]
"fenics/test-multiphenics*.py" = ["E402", "F403", "F405"]
"fenics/test-rbnics*.py" = ["E402", "F403", "F405"]
"firedrake/test-irksome*.py" = ["E402", "F403", "F405"]
"ngsolve/test-ngsolve*.py" = ["E402", "F403", "F405"]
"ngsolve/test-ngspetsc*.py" = ["E402", "F403", "F405"]
"ngsolve/test-ngsxfem*.py" = ["E402", "F403", "F405"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 120

[tool.ruff.lint.pydocstyle]
convention = "numpy"
