name: Release docker image of base environment

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      push:
        description: "Push the released image to docker registry (yes or no, default no)"
  workflow_call:
    inputs:
      push:
        description: "Push the released image to docker registry (yes or no, default no)"
        type: string

env:
  IMAGE_PREFIX: ghcr.io/isosafrasaurus/fem-on-jupyter/base

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Determine whether to push the released image to docker registry
        id: push
        run: |
          PUSH=${{ (inputs || github.event.inputs).push }}
          if [[ "${PUSH}" == "yes" ]]; then
            echo "push=yes" >> ${GITHUB_OUTPUT}
          else
            echo "push=no" >> ${GITHUB_OUTPUT}
          fi
        shell: bash
      - name: Build docker image
        run: |
          docker build --pull -t ${IMAGE_PREFIX}:latest -f base/Dockerfile .
      - name: Determine image tag
        if: github.repository == 'isosafrasaurus/fem-on-jupyter' && steps.push.outputs.push == 'yes'
        id: image_name
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          echo "image_tag=${IMAGE_TAG}" >> ${GITHUB_OUTPUT}
      - name: Log into the docker registry
        if: github.repository == 'isosafrasaurus/fem-on-jupyter' && steps.push.outputs.push == 'yes'
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push to the docker registry
        if: github.repository == 'isosafrasaurus/fem-on-jupyter' && steps.push.outputs.push == 'yes'
        run: |
          IMAGE_TAG="${{ steps.image_name.outputs.image_tag }}"
          docker tag ${IMAGE_PREFIX}:latest ${IMAGE_PREFIX}:${IMAGE_TAG}
          docker push ${IMAGE_PREFIX}:latest
          docker push ${IMAGE_PREFIX}:${IMAGE_TAG}
